PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <https://www.w3.org/2000/01/rdf-schema#>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX org: <https://www.w3.org/ns/org#>
PREFIX time: <https://www.w3.org/2006/time#>
PREFIX owl: <https://www.w3.org/2002/07/owl#>
PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX apf: <http://jena.apache.org/ARQ/property#>

CONSTRUCT {
?URI rdf:type doap:Project;
	frapo:hasCode ?code_du_projet;
	doap:name ?titre;
	dbp:shortName ?acronyme;
	?URI7 ?URI6;
	time:hasBeginning ?date_de_debut;
	time:hasEnd ?date_de_fin;
	doap:description ?resume;
	time:Duration ?duree;
	frapo:BudgetedAmount ?montant;
	foaf:topic ?theme;
	?URI8 ?code_rcn;
	doap:homepage ?lien_cordis;
	dcat:keyword ?mots_cles;
	org:linkedTo ?URI2.
?URI3 rdf:type owl:Thing;
	rdfs:label ?type_de_partenaire;
	frapo:hasCode ?code_du_type_de_partenaire.
?URI6 rdf:type owl:Class;
	rdfs:label ?appel_a_projet;
	frapo:hasCode ?code_d_appel_a_projet.
?URI5 rdf:type owl:DatatypeProperty.
?URI7 rdf:type owl:DatatypeProperty.
?URI8 rdf:type owl:DatatypeProperty;
	rdfs:range xsd:nonNegativeInteger.
?URI2 rdf:type dbo:Organisation;
	?URI5 ?identifiant_de_partenaire;
	rdfs:label ?libelle_de_partenaire;
	dbo:type ?URI3;
	dbo:locationCountry ?pays.
}
FROM <file:csv.csv>
WHERE {
  BIND (URI(CONCAT('http://ex.org/Projet/', ?code_du_projet)) AS ?URI)
  BIND (xsd:integer(?Id) AS ?code_du_projet)
  BIND (xsd:integer(?dureeInt) AS ?duree)
  BIND (xsd:float(?montantF) AS ?montant)
  BIND (URI(CONCAT('http://ex.org/Participants/', ?sigle_de_partenaire)) AS ?URI2)
  BIND(IF(bound(?pays_du_partenaire),?pays_du_partenaire,"null") AS ?test)
  ?separation apf:strSplit(?test ";")
  BIND(IF(?separation = "null",?nothing,URI(CONCAT('http://dbpedia.org/page/', ?separation))) AS ?pays)
  BIND (URI(CONCAT('http://ex.org/Participants/Type/', ?type_de_partenaire)) AS ?URI3)
  BIND (URI(CONCAT('http://ex.org/ontology/', ?type_d_identifiant)) AS ?URI5)
  BIND (URI(CONCAT('http://ex.org/Projet/Appel/', ?appel_a_projet)) AS ?URI6)
  BIND (URI('http://ex.org/ontology/Appel_Projet') AS ?URI7)
  BIND (URI('http://ex.org/ontology/Code_RCN') AS ?URI8)
}
