PREFIX dbp: <http://dbpedia.org/property/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX doap: <http://usefulinc.com/ns/doap#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/1999/02/22-rdf-syntax-ns#&gt>
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX apf: <http://jena.apache.org/ARQ/property#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX frapo: <http://purl.org/cerif/frapo/>
PREFIX time: <https://www.w3.org/2006/time#>

CONSTRUCT {

?URI_PROJECT rdf:type doap:Project;
	owl:sameAs ?URI_PROJECT_HORIZON;
	frapo:hasCode ?code_du_projet;
	doap:name ?titre;
	dbp:shortName ?Acronyme;
	
	frapo:hasCode ?code_d_appel_a_projet;
	xsd:string ?appel_a_projet;
	time:hasBeginning ?date_de_debut;
	time:hasEnd ?date_de_fin;
	doap:description ?resume;
	time:hasTemporalDuration ?duree;
	frapo:budgetedAmount ?montant;
	frapo:hasCode ?code_theme;
	foaf:topic ?theme;
	xsd:string ?code_RCN;
	doap:homepage ?lien_CORDIS;
	dcat:keyword ?mots_cles;
	org:linkedTo ?URI_Partenaire;
	?URI_Partenaire rdf:type ex:partenaire;
	     rdfs:subClassOf dbp:Agent;
	     doap:name ?libelle_de_partenaire;
	     ex:pays ?pays_du_partenaire.
}
FROM <file:test.csv>

WHERE {
	BIND(URI(CONCAT("https://data.enseignementsup-recherche.gouv.fr/explore/dataset/fr-esr-aap-fp7-projets-retenus-participants-identifies/", ?code_du_projet)) AS ?URI_PROJECT)
	BIND(URI(CONCAT("https://data.enseignementsup-recherche.gouv.fr/explore/dataset/appels-a-projets-horizon-2020-projets-retenus-et-participants-identifies/", ?code_du_projet)) AS ?URI_PROJECT_HORIZON)
	BIND(URI(CONCAT("https://ex.org/partenaire", ?libelle_de_partenaire)) AS ?URI_Partenaire)
	BIND(ex:pays rdfs:subClassOf dbo:Place)
	#apf:strSplit permet de gérer les multivalue d'une colonne et de les séparer, mais il semble
	#qu'il n'est possible de faire qu'un seul strSplit par dataset, hors nous avons deux attributs multivalues qui fonctionnent ensemble,
	#nous devons donc soit split les deux attributs simultanément ou ne pas les split du tout afin de garder une cohérence des données.
	#Et comme nous ne pouvons pas faire deux strSplit dans le même dataset, nous avons choisis de les laisser en multivalue.
	#?pays apf:strSplit (?pays_du_partenaire ";")
	#filter(BOUND(?pays_du_partenaire))
}
